export const Users = [
  {
    id: 1,
    name: "Van Manh",
    age: "20",
    imagelink: "link_to_image1.jpg",
    friend: 132,
  },
  {
    id: 2,
    name: "John Doe",
    age: "25",
    imagelink: "link_to_image2.jpg",
    friend: 85,
  },
  {
    id: 3,
    name: "Jane Smith",
    age: "30",
    imagelink: "link_to_image3.jpg",
    friend: 190,
  },
  {
    id: 4,
    name: "Alice Johnson",
    age: "22",
    imagelink: "link_to_image4.jpg",
    friend: 72,
  },
  {
    id: 5,
    name: "Bob Brown",
    age: "28",
    imagelink: "link_to_image5.jpg",
    friend: 156,
  },
  {
    id: 6,
    name: "Charlie Davis",
    age: "24",
    imagelink: "link_to_image6.jpg",
    friend: 134,
  },
  {
    id: 7,
    name: "Daisy Miller",
    age: "26",
    imagelink: "link_to_image7.jpg",
    friend: 89,
  },
  {
    id: 8,
    name: "Ella White",
    age: "21",
    imagelink: "link_to_image8.jpg",
    friend: 54,
  },
  {
    id: 9,
    name: "Frank Wilson",
    age: "27",
    imagelink: "link_to_image9.jpg",
    friend: 67,
  },
  {
    id: 10,
    name: "Grace Clark",
    age: "29",
    imagelink: "link_to_image10.jpg",
    friend: 200,
  },
  {
    id: 11,
    name: "Henry Lewis",
    age: "23",
    imagelink: "link_to_image11.jpg",
    friend: 103,
  },
  {
    id: 12,
    name: "Ivy Walker",
    age: "30",
    imagelink: "link_to_image12.jpg",
    friend: 45,
  },
  {
    id: 13,
    name: "Jack Hall",
    age: "22",
    imagelink: "link_to_image13.jpg",
    friend: 60,
  },
  {
    id: 14,
    name: "Kathy Young",
    age: "25",
    imagelink: "link_to_image14.jpg",
    friend: 99,
  },
  {
    id: 15,
    name: "Liam King",
    age: "28",
    imagelink: "link_to_image15.jpg",
    friend: 130,
  },
  {
    id: 16,
    name: "Mia Adams",
    age: "27",
    imagelink: "link_to_image16.jpg",
    friend: 115,
  },
  {
    id: 17,
    name: "Nathan Scott",
    age: "24",
    imagelink: "link_to_image17.jpg",
    friend: 92,
  },
  {
    id: 18,
    name: "Olivia Perez",
    age: "23",
    imagelink: "link_to_image18.jpg",
    friend: 58,
  },
  {
    id: 19,
    name: "Paul Baker",
    age: "29",
    imagelink: "link_to_image19.jpg",
    friend: 187,
  },
  {
    id: 20,
    name: "Quincy Turner",
    age: "21",
    imagelink: "link_to_image20.jpg",
    friend: 112,
  },
];
export const Friends = [
  {
    id: 21,
    name: "Đường Tank",
    age: "20",
    imagelink: "link_to_image1.jpg",
    friend: 132,
  },
  {
    id: 22,
    name: "Như Lai",
    age: "25",
    imagelink: "link_to_image2.jpg",
    friend: 85,
  },
  {
    id: 23,
    name: "Bồ Tát",
    age: "30",
    imagelink: "link_to_image3.jpg",
    friend: 190,
  },
]